# Generated by Django 5.1.15 on 2026-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintauditlog',
            name='timestamp_iso',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
