# Generated by Django 5.1.15 on 2026-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaintauditlog_timestamp_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='original_description',
            field=models.TextField(blank=True, help_text='Preserved verbatim citizen submission'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translated_description',
            field=models.TextField(blank=True, help_text='Standardized English description'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translated_title',
            field=models.CharField(blank=True, help_text='Standardized English title', max_length=250),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translation_header',
            field=models.CharField(blank=True, help_text='Automated translation disclaimer and attribution', max_length=350),
        ),
        migrations.AddField(
            model_name='complaint',
            name='unicode_script_range',
            field=models.CharField(blank=True, default='U+0020–U+007F', max_length=50),
        ),
    ]
