# Generated by Django 5.1.15 on 2026-09-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_original_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_hash', models.CharField(db_index=True, max_length=64)),
                ('aadhaar_last4', models.CharField(max_length=4)),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='SIGNUP', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='aadhaar_last4',
            field=models.CharField(blank=True, help_text='Masked Aadhaar display XXXX-XXXX-1234', max_length=4),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated_to_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current officer hierarchy level assigned (1: Junior Ward, 2: Zonal Officer, 3: Commissioner)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False, help_text='Complainant authenticated via UIDAI Aadhaar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of 12-digit Aadhaar for deduplication & verification lookup', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, help_text='Masked Aadhaar display XXXX-XXXX-1234', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hierarchy_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1: Junior Staff / Ward Field Staff (AE/JE/SI)'), (2, 'Level 2: Middle Management / Zonal Officer (EE/ZO)'), (3, 'Level 3: Senior Management / Commissioner / Dept Head (SE/Comm)')], default=1, help_text='Departmental Hierarchy Tier for SLA Escalation (+1 Level Staff)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False, help_text='Whether this citizen account has completed UIDAI OTP authentication'),
        ),
    ]
