# Generated by Django 5.1.15 on 2026-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_helpline_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='current_level',
            field=models.CharField(choices=[('DL1', 'Department Level 1 (DL1 - Concerned Department)'), ('DL2', 'Department Level 2 (DL2 - DL1 + 1)'), ('DL3', 'Department Level 3 (DL3 - DL2 + 1)'), ('CL1', 'City Level 1 (CL1 - All DL3 + 1)'), ('CL2', 'City Level 2 (CL2 - CL1 + 1)'), ('CL3', 'City Level 3 (CL3 - CL2 + 1)'), ('CM_OFFICE', 'Escalated to CM Office (Apex Review)')], db_index=True, default='DL1', help_text='Current Sequential Escalation Level: DL1 -> DL2 -> DL3 -> CL1 -> CL2 -> CL3 -> CM_OFFICE', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='level_sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='SLA hours allocated specifically for the current escalation level'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='escalated_to_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current officer hierarchy level integer (1: DL1, 2: DL2, 3: DL3, 4: CL1, 5: CL2, 6: CL3, 7: CM_OFFICE)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hierarchy_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DL1: Department Level 1 (Ward/Junior AE)'), (2, 'DL2: Department Level 2 (Assistant Executive Engineer)'), (3, 'DL3: Department Level 3 (Executive Engineer / Zonal Head)'), (4, 'CL1: City Level 1 (Citywide Dept Head / Joint Commissioner)'), (5, 'CL2: City Level 2 (Deputy / Additional Commissioner)'), (6, 'CL3: City Level 3 (Municipal Commissioner)'), (7, 'CM_OFFICE: Chief Minister Executive Cell (Apex Level)')], default=1, help_text='Departmental Hierarchy Tier for SLA Escalation (DL1..CL3, CM_OFFICE)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'State SuperAdmin'), ('COMMISSIONER', 'Municipal Commissioner (CL3)'), ('ZONAL_OFFICER', 'Zonal Officer (DL3)'), ('WARD_OFFICER', 'Ward / Dept Officer (DL1/DL2)'), ('FIELD_STAFF', 'Field Verification Staff (DL1)'), ('CM_OFFICE', 'Chief Minister Special Cell (CM Office)'), ('POLICYMAKER', 'State / National Policymaker'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=30),
        ),
    ]
