# Generated by Django 5.1.15 on 2026-09-30 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_complaint_current_level_complaint_level_sla_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentbroadcast',
            name='benefits',
            field=models.TextField(blank=True, help_text='Details of financial/in-kind/service benefits offered'),
        ),
        migrations.AddField(
            model_name='governmentbroadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governmentbroadcast',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department publishing this alert or welfare scheme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='core.department'),
        ),
        migrations.AddField(
            model_name='governmentbroadcast',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Eligibility conditions for welfare scheme beneficiaries'),
        ),
        migrations.AddField(
            model_name='governmentbroadcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='governmentbroadcast',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start timestamp from which this alert/scheme is active'),
        ),
        migrations.AlterField(
            model_name='governmentbroadcast',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Expiry or application deadline timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'State SuperAdmin'), ('DEPT_ADMIN', 'Departmental Administrator'), ('COMMISSIONER', 'Municipal Commissioner (CL3)'), ('ZONAL_OFFICER', 'Zonal Officer (DL3)'), ('WARD_OFFICER', 'Ward / Dept Officer (DL1/DL2)'), ('FIELD_STAFF', 'Field Verification Staff (DL1)'), ('CM_OFFICE', 'Chief Minister Special Cell (CM Office)'), ('POLICYMAKER', 'State / National Policymaker'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=30),
        ),
    ]
