# Generated by Django 5.1.15 on 2026-09-30 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_governmentbroadcast_benefits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalprojectrecommendation',
            name='is_planned',
            field=models.BooleanField(db_index=True, default=False, help_text='Added to Policymaker Planned Work List'),
        ),
        migrations.AddField(
            model_name='capitalprojectrecommendation',
            name='planned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitalprojectrecommendation',
            name='planned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_capital_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitalprojectrecommendation',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed / Identified by AI'), ('PLANNED', 'Planned Work'), ('UNDER_REVIEW', 'Under Review by Department'), ('SANCTIONED', 'Budget Sanctioned'), ('TENDERED', 'Tender Floated'), ('IN_EXECUTION', 'Work in Progress'), ('COMPLETED', 'Completed')], default='PROPOSED', max_length=30),
        ),
    ]
