# Generated by Django 5.1.15 on 2026-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_capitalprojectrecommendation_is_planned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyTicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_code', models.CharField(db_index=True, default='GCC', max_length=30)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yearly Ticket Sequence',
                'verbose_name_plural': 'Yearly Ticket Sequences',
                'unique_together': {('cluster_code', 'year')},
            },
        ),
    ]
