# Generated by Django 5.1.15 on 2026-09-30 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_yearlyticketsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='audit_notes',
            field=models.TextField(blank=True, help_text='Auditor findings, policy compliance notes and directives'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audit_status',
            field=models.CharField(choices=[('NOT_AUDITED', 'Not Audited'), ('UNDER_REVIEW', 'Under Audit Review'), ('COMPLIANT', 'Compliant with Policies'), ('FLAGGED_NON_COMPLIANT', 'Flagged Non-Compliant')], db_index=True, default='NOT_AUDITED', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'State SuperAdmin'), ('DEPT_ADMIN', 'Departmental Administrator'), ('COMMISSIONER', 'Municipal Commissioner (CL3)'), ('ZONAL_OFFICER', 'Zonal Officer (DL3)'), ('WARD_OFFICER', 'Ward / Dept Officer (DL1/DL2)'), ('FIELD_STAFF', 'Field Verification Staff (DL1)'), ('CM_OFFICE', 'Chief Minister Special Cell (CM Office)'), ('POLICYMAKER', 'State / National Policymaker'), ('AUDITOR', 'Statutory / Compliance Auditor'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SLA_BREACH', 'SLA Breach / Unaddressed Escalation'), ('MISSING_PROOF', 'Missing Mandatory Resolution Proof / Photo'), ('PREMATURE_CLOSURE', 'Suspect Premature Closure without Verification'), ('GEOSPATIAL_MISMATCH', 'Geospatial or DIGIPIN Inaccuracy'), ('PROCEDURAL_VIOLATION', 'Departmental Procedural Violation'), ('DATA_INTEGRITY', 'Data Integrity / Cryptographic Discrepancy'), ('OTHER', 'General Policy Non-Compliance')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical / Statutory Non-Compliance')], default='MEDIUM', max_length=20)),
                ('observation', models.TextField(help_text='Detailed audit observation and rule/policy violation notes')),
                ('action_required', models.TextField(blank=True, help_text='Corrective or remediation action required from department')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_audit_findings', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='core.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
