# Generated by Django 5.1.15 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_complaintauditlog_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
    ]
