apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dpig-web-hpa
  namespace: dpig
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dpig-web
  minReplicas: 3
  maxReplicas: 25
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dpig-celery-worker-hpa
  namespace: dpig
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dpig-celery-worker
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
